# Task 2
This serves as a template which will guide you through the implementation of this task. It is advised to first read the whole template and get a sense of the overall structure of the code before trying to fill in any of the TODO gaps.
This is the jupyter notebook version of the template. For the python file version, please refer to the file `template_solution.py`.

First, we import necessary libraries:

In [87]:
import numpy as np
import pandas as pd
# Add any other imports you need here
from sklearn.preprocessing import OneHotEncoder
from sklearn import linear_model, model_selection
from sklearn.model_selection import KFold
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import DotProduct, RBF, Matern, RationalQuadratic

In [19]:
#Test: changing season into 4 binary columns

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

train_df = pd.read_csv("train.csv")


# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Fit and transform the data
one_hot_encoded = encoder.fit_transform(train_df[['season']])

# Convert the one-hot encoded array into a DataFrame
one_hot_encoded_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(['season']))

# Concatenate the one-hot encoded DataFrame with the original DataFrame
train_df = pd.concat([train_df, one_hot_encoded_df], axis=1)

# Drop the original column 
train_df.drop('season', axis=1, inplace=True)

# Print the resulting DataFrame
print(train_df.head(6))

   price_AUS  price_CHF  price_CZE  price_GER  price_ESP  price_FRA  price_UK  \
0        NaN   9.644028  -1.686248  -1.748076  -3.666005        NaN -1.822720   
1        NaN   7.246061  -2.132377  -2.054363  -3.295697  -4.104759 -1.826021   
2  -2.101937   7.620085  -1.910282        NaN  -3.388777        NaN -2.034409   
3  -2.098475   8.411894  -1.903834        NaN  -3.588235        NaN -2.214720   
4  -1.969687   8.926884  -1.697257  -1.331049        NaN  -3.911096 -2.388092   
5  -1.935209   8.104719  -1.488434        NaN  -3.878786  -3.831497 -2.275584   

   price_ITA  price_POL  price_SVK  season_autumn  season_spring  \
0  -3.931031        NaN  -3.238197            0.0            1.0   
1        NaN        NaN  -3.212894            0.0            0.0   
2  -4.073850        NaN  -3.114061            1.0            0.0   
3  -4.018620  -2.330803        NaN            0.0            0.0   
4  -4.093946        NaN        NaN            0.0            1.0   
5  -4.014349        NaN 

/Users/nicolazolliker/anaconda3/envs/iml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


# Data Loading
TODO: Perform data preprocessing, imputation and extract X_train, y_train and X_test
(and potentially change initialization of variables to accomodate how you deal with non-numeric data)

In [59]:
"""
This loads the training and test data, preprocesses it, removes the NaN
values and interpolates the missing data using imputation

Parameters
----------
Compute
----------
X_train: matrix of floats, training input with features
y_train: array of floats, training output with labels
X_test: matrix of floats: dim = (100, ?), test input with features
"""
# Load training data
train_df = pd.read_csv("train.csv")

    
# Load test data
test_df = pd.read_csv("test.csv")


# Dummy initialization of the X_train, X_test and y_train   
# TODO: Depending on how you deal with the non-numeric data, you may want to 
# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the data
one_hot_encoded1 = encoder.fit_transform(train_df[['season']])
one_hot_encoded2 = encoder.fit_transform(test_df[['season']])

# Convert the one-hot encoded array into a DataFrame
one_hot_encoded_df1 = pd.DataFrame(one_hot_encoded1, columns=encoder.get_feature_names_out(['season']))
one_hot_encoded_df2 = pd.DataFrame(one_hot_encoded2, columns=encoder.get_feature_names_out(['season']))

# Concatenate the one-hot encoded DataFrame with the original DataFrame
train_df = pd.concat([train_df, one_hot_encoded_df1], axis=1)
test_df = pd.concat([test_df, one_hot_encoded_df2], axis=1)

# Drop the original column 
train_df.drop('season', axis=1, inplace=True)
test_df.drop('season', axis=1, inplace=True)


# modify/ignore the initialization of these variables   
X_train = np.zeros_like(train_df.drop(['price_CHF'],axis=1))
y_train = np.zeros_like(train_df['price_CHF'])
X_test = np.zeros_like(test_df)

# TODO: Perform data preprocessing, imputation and extract X_train, y_train and X_test
#kNN imputation
imputer = KNNImputer(n_neighbors=5, weights="uniform")
imputed_data = imputer.fit_transform(train_df)
train_df = pd.DataFrame(imputed_data, columns=train_df.columns)
#transform to numpy
X_train = train_df.drop(['price_CHF'],axis=1).values
y_train = train_df['price_CHF'].values

imputed_data = imputer.fit_transform(test_df)
test_df = pd.DataFrame(imputed_data, columns=test_df.columns)
#transform to numpy
X_test = test_df.values


assert (X_train.shape[1] == X_test.shape[1]) and (X_train.shape[0] == y_train.shape[0]) and (X_test.shape[0] == 100), "Invalid data shape"

/Users/nicolazolliker/anaconda3/envs/iml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/Users/nicolazolliker/anaconda3/envs/iml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [99]:

print(X_train)

[[-2.12086072 -1.6862481  -1.74807638 ...  1.          0.
   0.        ]
 [-2.12490715 -2.13237679 -2.05436269 ...  0.          1.
   0.        ]
 [-2.10193661 -1.91028232 -1.90464383 ...  0.          0.
   0.        ]
 ...
 [-0.97115692  0.24527874  0.55847439 ...  0.          1.
   0.        ]
 [-1.16316339  0.29991092  0.78815177 ...  0.          0.
   0.        ]
 [-1.05834258  0.23183488  0.80046006 ...  0.          0.
   1.        ]]


# Modeling and Prediction
TODO: Define the model and fit it using training data. Then, use test data to make predictions

In [115]:
"""
This defines the model, fits training data and then does the prediction
with the test data 

Parameters
----------
X_train: matrix of floats, training input with 10 features
y_train: array of floats, training output
X_test: matrix of floats: dim = (100, ?), test input with 10 features

Compute
----------
y_test: array of floats: dim = (100,), predictions on test set
"""

y_pred=np.zeros(X_test.shape[0])
#TODO: Define the model and fit it using training data. Then, use test data to make predictions



kernel = [DotProduct(), Matern(), RBF(), RationalQuadratic()]
score = np.zeros((5, 4))
kf = KFold(n_splits=5)
j=0
for ker in kernel:
    i=0
    for train, test in kf.split(X_train):
        x_cv, x_valid, y_cv, y_valid = X_train[train], X_train[test], y_train[train], y_train[test]
        gpr = GaussianProcessRegressor(kernel=ker, n_restarts_optimizer = 3, random_state=42)
        gpr.fit(x_cv, y_cv)
        score[i, j] = gpr.score(x_valid, y_valid)
        i+=1
    j+=1

print(score)
print(np.mean(score, axis=0))


assert y_pred.shape == (100,), "Invalid data shape"

/Users/nicolazolliker/anaconda3/envs/iml/lib/python3.10/site-packages/sklearn/gaussian_process/kernels.py:419: ConvergenceWarning: The optimal value found for dimension 0 of parameter sigma_0 is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


[[0.87755586 0.97523028 0.93928585 0.97545642]
 [0.90645666 0.93769499 0.85018023 0.94884852]
 [0.78883046 0.93081321 0.8843229  0.92003786]
 [0.89476601 0.97350736 0.91091743 0.97491152]
 [0.89718432 0.96781547 0.91414042 0.97259058]]
[0.87295866 0.95701226 0.89976937 0.95836898]


In [116]:
gpr = GaussianProcessRegressor(kernel=RationalQuadratic(), n_restarts_optimizer = 3, random_state=42)
gpr.fit(X_train, y_train)
y_pred = gpr.predict(X_test)
print(gpr.score(X_train, y_train))
print(y_pred)

1.0
[-1.98141438 -2.3463881  -2.16027946 -0.56083042 -1.85409909 -2.21389668
 -1.4336032   0.40344909  0.01194165  1.12006565  0.83905146  2.75164227
  2.42790329  2.36704096  2.68664557  1.88051356  1.78646949  1.89615268
  2.02966716  1.68483959  2.94215123  3.21006164  3.42328874  3.05548692
  3.21032907  4.7405807   5.73818546  7.85939997  8.91027591  9.16855706
  9.01049908  7.82563577  7.83746999  7.45292347  7.79665008  7.72958618
  7.51630049  7.96117217  7.86521161  7.27419403  7.75828945  7.6442071
  7.84180259  7.7702496   7.79919726  8.0966771   7.70314657  8.13663766
  7.7629115   7.85225181  7.50884881  7.73309607  7.64679106  8.56907402
  7.9247738   9.01739351  8.40676528  8.11544513  6.93099624  6.36473014
  6.94012534  5.7478381   5.37925013  5.47215219  5.20779917  5.2556912
  4.67550823  4.76457154  4.16667342  5.3299426   4.41704359  5.31858056
  3.82480592  5.65373381  5.73185369  6.30247515  7.52730375  7.52380868
  8.07635139  8.29110888  8.34287899  8.36368623 

# Saving Results
You don't have to change this

In [113]:
dt = pd.DataFrame(y_pred) 
dt.columns = ['price_CHF']
dt.to_csv('results_nicola_kNN.csv', index=False)
print("\nResults file successfully generated!")


Results file successfully generated!
